# Generated by Django 5.2 on 2025-05-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_detectionhistory_result_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionhistory',
            name='image',
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='result_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='results/'),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='source_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='source_type',
            field=models.CharField(choices=[('image', 'Фото'), ('video', 'Видео'), ('rtsp', 'RTSP')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='result_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
